Convert all to upercase
Lite changes, converting all vars in UPPERCASE

Some body add changes in lowercase and somebody make changes in uppercase

As I make some vars inconsitent I try change all to UPPER

diff --git a/v-restore-cpanel-v2 b/v-restore-cpanel-v2
--- a/v-restore-cpanel-v2
+++ b/v-restore-cpanel-v2
@@ -1,6 +1,7 @@
 #!/bin/bash
 # info: Import Cpanel backup to a new user
-# options: BACKUP [MX]
+# options: BACKUP [ALL] [DB] [DOMAIN] [CRON] [MAIL] [MX]
+
 #
 # example: v-import-cpanel /backup/backup.tar.gz yes
 #
@@ -9,7 +10,6 @@
 # Thanks to <https://github.com/Skamasle/sk-import-cpanel-backup-to-vestacp/graphs/contributors>
 
 # Known issue
-# - Importing certificates fails at the moment. Due to format changes of CPanel side
 # - It doesn't update DKIM
 
 # shellcheck source=/usr/local/hestia/func/main.sh
@@ -115,13 +115,13 @@ else
 fi
 
 # Create a new user
-tmp_passwd=$(generate_password)
+TMP_PASSWD=$(generate_password)
 email=$(cat ./cp/$NEW_USER | grep CONTACTEMAIL= | cut -f2 -d'=')
 if [ -z "$email" ]; then
 	# Hestia does not like email to be set to an empty string
 	email="info@"$(hostname)
 fi
-$BIN/v-add-user "$NEW_USER" "$tmp_passwd" "$email" "$HESTIA_PACKAGE"
+$BIN/v-add-user "$NEW_USER" "$TMP_PASSWD" "$email" "$HESTIA_PACKAGE"
 if [ "$?" -ne 0 ]; then
 	printf "\n%sERROR%s: Unable to create user" "$GREEN" "$COLOROFF"
 	exit 1
@@ -144,11 +144,11 @@ grep "GRANT" mysql.sql | grep -v "USAGE ON" > u_db
 cat u_db | awk -F "'" '{ print $2, $4 }' | sort | uniq > uni_u_db
 sed -i "/$NEW_USER /d" user_password_db
 # Get database list
-db_list=$(grep -m 1 Database: mysql/*.create | awk '{ print  $5 }')
+DB_LIST=$(grep -m 1 Database: mysql/*.create | awk '{ print  $5 }')
 # Fix mysql 8 to mariadb problems here:
 sed -i "s/utf8mb4_0900_ai_ci/utf8mb4_unicode_ci/g" mysql/*
 mysql -e "SHOW DATABASES" > server_dbs
-for db in $db_list; do
+for db in $DB_LIST; do
 	grep -w $db server_dbs
 	if [ $? == "1" ]; then
 		printf "%sINFO%s: Create and restore %s\n" "$GREEN" "$COLOROFF" "${db}"
@@ -178,41 +178,41 @@ $BIN/v-rebuild-databases $NEW_USER
 
 restore_domains(){
 printf "\n%sINFO:%s Start Restoring Domains\n" "$GREEN" "$COLOROFF"
-addon_domains=$(cat addons | cut -d "=" -f1)
+# ADDON_DOMAINSs=$(cat addons | cut -d "=" -f1)
 sed -i 's/_/./g; s/=/ /g' addons
 printf "%sINFO:%s Converting addons domains, subdomains and some other fun\n" "$GREEN" "$COLOROFF"
 cp sds hst_sds
 cp sds2 hst_sds2
 sed -i 's/_/./g' hst_sds
-cat addons | while read addon_domain addon_sub; do
-printf "%sINFO:%s Converting default subdomain: %s in domain: %s\n" "$GREEN" "$COLOROFF" "$addon_sub"  "$addon_domain"
-	sed -i -e "s/$addon_sub/$addon_domain/g" hst_sds
-	sed -i -e "s/$addon_sub/$addon_domain/g" hst_sds2
-	mv userdata/$addon_sub userdata/${addon_domain}
-	mv apache_tls/$addon_sub apache_tls/${addon_domain}
+cat addons | while read ADDON_DOMAINS ADDON_SUB; do
+printf "%sINFO:%s Converting default subdomain: %s in domain: %s\n" "$GREEN" "$COLOROFF" "$ADDON_SUB"  "$ADDON_DOMAINS"
+	sed -i -e "s/$ADDON_SUB/$ADDON_DOMAINS/g" hst_sds
+	sed -i -e "s/$ADDON_SUB/$ADDON_DOMAINS/g" hst_sds2
+	mv userdata/$ADDON_SUB userdata/${ADDON_DOMAINS}
+	mv apache_tls/$ADDON_SUB apache_tls/${ADDON_DOMAINS}
 done
 sed -i 's/public_html/public@html/g; s/_/./g; s/public@html/public_html/g; s/=/ /g' hst_sds2
 
 function get_domain_path() {
-	while read cp_domain path; do
-		printf "%sINFO:%s Import $cp_domain\n" "$GREEN" "$COLOROFF"
-		if [ -e userdata/$cp_domain ]; then
-			$BIN/v-add-domain "$NEW_USER" "$cp_domain"
+	while read CP_DOMAIN path; do
+		printf "%sINFO:%s Import $CP_DOMAIN\n" "$GREEN" "$COLOROFF"
+		if [ -e userdata/$CP_DOMAIN ]; then
+			$BIN/v-add-domain "$NEW_USER" "$CP_DOMAIN"
 			if [ $? -ne 0 ]; then
 				check_result "1" "Unable to create domain it allready exists"
 			fi
-			rm -f /home/$NEW_USER/web/$cp_domain/public_html/index.html
-			rm -f /home/$NEW_USER/web/$cp_domain/public_html/robots.txt
+			rm -f /home/$NEW_USER/web/$CP_DOMAIN/public_html/index.html
+			rm -f /home/$NEW_USER/web/$CP_DOMAIN/public_html/robots.txt
 			sync_count=0
-			rsync -av homedir/$path/ /home/$NEW_USER/web/$cp_domain/public_html 2>&1 \
+			rsync -av homedir/$path/ /home/$NEW_USER/web/$CP_DOMAIN/public_html 2>&1 \
 				| while read file_dm; do
 					sync_count=$(($sync_count + 1))
 					echo -en "-- $sync_count restored files\r"
 				done
-			chown $NEW_USER:$NEW_USER -R /home/$NEW_USER/web/$cp_domain/public_html
-			chown $NEW_USER:www-data /home/$NEW_USER/web/$cp_domain/public_html
-			chmod 751 /home/$NEW_USER/web/$cp_domain/public_html
-			echo "$cp_domain" >> exclude_path
+			chown $NEW_USER:$NEW_USER -R /home/$NEW_USER/web/$CP_DOMAIN/public_html
+			chown $NEW_USER:www-data /home/$NEW_USER/web/$CP_DOMAIN/public_html
+			chmod 751 /home/$NEW_USER/web/$CP_DOMAIN/public_html
+			echo "$CP_DOMAIN" >> exclude_path
 		fi
 	done
 }
@@ -316,76 +316,77 @@ restore_mail() {
 printf "\n%sINFO:%s Start Restoring Mails\n" "$GREEN" "$COLOROFF"
 cd homedir/mail
 
-for folder in *; do
-	if [ -d "$folder" ]; then
-		if [[ "$folder" != "cur" && "$folder" != "new" && "$folder" != "tmp" ]]; then
-			printf "%sINFO:%s Restore mails for domain: %s \n" "$GREEN" "$COLOROFF" $folder
+for FOLDER in *; do
+	if [ -d "$FOLDER" ]; then
+		if [[ "$FOLDER" != "cur" && "$FOLDER" != "new" && "$FOLDER" != "tmp" ]]; then
+			printf "%sINFO:%s Restore mails for domain: %s \n" "$GREEN" "$COLOROFF" $FOLDER
             # This is needed as parked domains have emails but not added 
-            if ! $BIN/v-list-mail-domains $NEW_USER plain | awk '{ print $1 }' |grep -q "^${folder}$"; then
-	        	printf "%sINFO:%s Found parked domain %s adding as mail domain in Hestia\n" "$GREEN" "$COLOROFF" "$folder"
-	            $BIN/v-add-mail-domain $NEW_USER $folder	    
+            if ! $BIN/v-list-mail-domains $NEW_USER plain | awk '{ print $1 }' |grep -q "^${FOLDER}$"; then
+	        	printf "%sINFO:%s Found parked domain %s adding as mail domain in Hestia\n" "$GREEN" "$COLOROFF" "$FOLDER"
+	            $BIN/v-add-mail-domain $NEW_USER $FOLDER	    
 	        fi
-			cd $folder
-			mail_account_count=$(find . -maxdepth 1 -mindepth 1 -type d \( ! -name cur ! -name new ! -name tmp \) | wc -l)
-			if [ "$mail_account_count" -eq 0 ]; then
-				printf "%sINFO:%s No mail accounts to restore for domain%s\n" "$GREEN" "$COLOROFF" "$folder"
+			cd $FOLDER
+			MAIL_ACCOUNT_COUNT=$(find . -maxdepth 1 -mindepth 1 -type d \( ! -name cur ! -name new ! -name tmp \) | wc -l)
+			if [ "$MAIL_ACCOUNT_COUNT" -eq 0 ]; then
+				printf "%sINFO:%s No mail accounts to restore for domain%s\n" "$GREEN" "$COLOROFF" "$FOLDER"
 				cd ..
 				continue
 			fi
 
-			for mail_account in *; do
-				printf "%sINFO:%s Import mail account: %s@%s\n" "$GREEN" "$COLOROFF" "$mail_account" "$folder"
+			for MAIL_ACCOUNT in *; do
+				printf "%sINFO:%s Import mail account: %s@%s\n" "$GREEN" "$COLOROFF" "$MAIL_ACCOUNT" "$FOLDER"
 				# Doesn't really matter but we don't know the unhashed one
-				tmp_pass=$(generate_password)
-				$BIN/v-add-mail-account $NEW_USER $folder $mail_account $tmp_pass
-				mv $mail_account /home/$NEW_USER/mail/$folder/
-				chown -R $NEW_USER:mail /home/$NEW_USER/mail/$folder/
+				TMP_PASSWD=$(generate_password)
+				$BIN/v-add-mail-account $NEW_USER $FOLDER $MAIL_ACCOUNT $TMP_PASSWD
+				mv $MAIL_ACCOUNT /home/$NEW_USER/mail/$FOLDER/
+				chown -R $NEW_USER:mail /home/$NEW_USER/mail/$FOLDER/
 
 				# Decompress gzipped emails
-				decompressed_count=0
-				for mail_file in $(find /home/$NEW_USER/mail/$folder -type f); do
-					if file "$mail_file" | grep -q "gzip compressed"; then
-						original_time=$(stat -c %y "$mail_file" 2> /dev/null)
-						gunzip -c "$mail_file" > "${mail_file}.decompressed" && mv "${mail_file}.decompressed" "$mail_file"
+				DECOMPRESSED_COUNT=0
+				for MAIL_FILE in $(find /home/$NEW_USER/mail/$FOLDER -type f); do
+					if file "$MAIL_FILE" | grep -q "gzip compressed"; then
+						original_time=$(stat -c %y "$MAIL_FILE" 2> /dev/null)
+						gunzip -c "$MAIL_FILE" > "${MAIL_FILE}.decompressed" && mv "${MAIL_FILE}.decompressed" "$MAIL_FILE"
 						if [ ! -z "$original_time" ]; then
-							touch -d "$original_time" "$mail_file"
+							touch -d "$original_time" "$MAIL_FILE"
 						fi
-						((decompressed_count++))
+						((DECOMPRESSED_COUNT++))
 					fi
 				done
 
-				printf "%sINFO:%s %s emails decompressed for %s@%s\n" "$GREEN" "$COLOROFF" "$decompressed_count" "$mail_account" "$folder"
+				printf "%sINFO:%s %s emails decompressed for %s@%s\n" "$GREEN" "$COLOROFF" "$DECOMPRESSED_COUNT" "$MAIL_ACCOUNT" "$FOLDER"
 
-				find /home/$NEW_USER/mail/$folder -type f -name 'dovecot*' -delete
+				find /home/$NEW_USER/mail/$FOLDER -type f -name 'dovecot*' -delete
 
 				# Extract and update password from the shadow file
-				password_file="../../etc/${folder}/shadow"
-				if [ -f "$password_file" ]; then
-					pass_line=$(grep "^$mail_account:" $password_file)
+				PASSWORD_FILE="../../etc/${FOLDER}/shadow"
+				if [ -f "$PASSWORD_FILE" ]; then
+					PASS_LINE=$(grep "^$MAIL_ACCOUNT:" $PASSWORD_FILE)
 					if [ $? -eq 0 ]; then
 						# Extract the hashed password from the shadow file
-						pass=$(echo "$pass_line" | awk -F ":" '{print $2}')
-						newline="${mail_account}:{SHA512-CRYPT}$pass:${NEW_USER}:mail::/home/${NEW_USER}:0"
-						newline2="ACCOUNT='${mail_account}' ALIAS='' AUTOREPLY='no' FWD='' FWD_ONLY='' MD5='{SHA512-CRYPT}$pass' QUOTA='unlimited' U_DISK='0' SUSPENDED='no' TIME='$time' DATE='$date'"
-						escaped=$(printf '%s\n' "$newline" | sed -e 's/[\/&]/\\&/g')
-						escaped2=$(printf '%s\n' "$newline2" | sed -e 's/[\/&]/\\&/g')
-						sed -i "s/^${mail_account}:.*/$escaped/g" /home/${NEW_USER}/conf/mail/${folder}/passwd
-						sed -i "s/^ACCOUNT='${mail_account}.*/$escaped2/g" /usr/local/hestia/data/users/${NEW_USER}/mail/${folder}.conf
+						pass=$(echo "$PASS_LINE" | awk -F ":" '{print $2}')
+						NEW_LINE="${MAIL_ACCOUNT}:{SHA512-CRYPT}$pass:${NEW_USER}:mail::/home/${NEW_USER}:0"
+						NEW_LINE2="ACCOUNT='${MAIL_ACCOUNT}' ALIAS='' AUTOREPLY='no' FWD='' FWD_ONLY='' MD5='{SHA512-CRYPT}$pass' QUOTA='unlimited' U_DISK='0' SUSPENDED='no' TIME='$time' DATE='$date'"
+						escaped=$(printf '%s\n' "$NEW_LINE" | sed -e 's/[\/&]/\\&/g')
+						escaped2=$(printf '%s\n' "$NEW_LINE2" | sed -e 's/[\/&]/\\&/g')
+						sed -i "s/^${MAIL_ACCOUNT}:.*/$escaped/g" /home/${NEW_USER}/conf/mail/${FOLDER}/passwd
+						sed -i "s/^ACCOUNT='${MAIL_ACCOUNT}.*/$escaped2/g" /usr/local/hestia/data/users/${NEW_USER}/mail/${FOLDER}.conf
 					else
-						printf "%sWarning:%s Password for %s@%s not found in shadow file.\n" "$YELLOW" "$COLOROFF" "$mail_account" "$folder"
+						printf "%sWarning:%s Password for %s@%s not found in shadow file.\n" "$YELLOW" "$COLOROFF" "$MAIL_ACCOUNT" "$FOLDER"
 					fi
 				else
-					printf "%sWarning:%s Shadow file for %s not found.\n" "$YELLOW" "$COLOROFF" "$folder"
+					printf "%sWarning:%s Shadow file for %s not found.\n" "$YELLOW" "$COLOROFF" "$FOLDER"
 				fi
 			done
 			cd ..
-			$BIN/v-rebuild-mail-domain $NEW_USER $folder
+			$BIN/v-rebuild-mail-domain $NEW_USER $FOLDER
 		fi
 	fi
 done
 }
 
 restore_mx() {
+# By default there is no site in a script when $mx is defined
 if [ "$mx" = 'yes' ]; then
 	cd $MAIN_DIR/dnszones
 	for domain in $($BIN/v-list-mail-domains $NEW_USER plain | awk '{ print  $1 }'); do
@@ -416,18 +417,18 @@ CRON_DIR="$MAIN_DIR/cron"
 cd "$CRON_DIR"
 CRON_FILE="${NEW_USER}"
 if [ -f "$CRON_FILE" ] && [ -s "$CRON_FILE" ]; then
-	while IFS= read -r cron_job || [ -n "$cron_job" ]; do
-		[[ "$cron_job" =~ ^(#.*|\s*|MAILTO=.*|SHELL=.*)$ ]] && continue
+	while IFS= read -r CRON_JOB || [ -n "$CRON_JOB" ]; do
+		[[ "$CRON_JOB" =~ ^(#.*|\s*|MAILTO=.*|SHELL=.*)$ ]] && continue
 
-		min=$(echo "$cron_job" | awk '{print $1}')
-		hour=$(echo "$cron_job" | awk '{print $2}')
-		day=$(echo "$cron_job" | awk '{print $3}')
-		month=$(echo "$cron_job" | awk '{print $4}')
-		dow=$(echo "$cron_job" | awk '{print $5}')
-		cmd=$(echo "$cron_job" | awk '{for (i=6; i<=NF; i++) printf $i " "; print ""}')
+		MIN=$(echo "$CRON_JOB" | awk '{print $1}')
+		HOUR=$(echo "$CRON_JOB" | awk '{print $2}')
+		DAY=$(echo "$CRON_JOB" | awk '{print $3}')
+		MONTH=$(echo "$CRON_JOB" | awk '{print $4}')
+		DOW=$(echo "$CRON_JOB" | awk '{print $5}')
+		CMD=$(echo "$CRON_JOB" | awk '{for (i=6; i<=NF; i++) printf $i " "; print ""}')
 		#This try fix PHP crons converting cpanel paths to hestia paths
-        if [[ $cmd =~ "ea-php" ]]; then
-            EAPHP=$(echo $cmd | awk '{ print $1 }')
+        if [[ $CMD =~ "ea-php" ]]; then
+            EAPHP=$(echo $CMD | awk '{ print $1 }')
             # /opt/cpanel/ea-php70/root/bin/php
             # /usr/local/bin/ea-php70
             # default hestia /usr/bin/php
@@ -448,12 +449,12 @@ if [ -f "$CRON_FILE" ] && [ -s "$CRON_FILE" ]; then
             vPHP=$(echo /usr/bin/php${N1}.${N2})
             
             if [ -e $vPHP ]; then
-                cmd=$(echo $cmd | sed "s#$EAPHP#$vPHP#")
+                CMD=$(echo $CMD | sed "s#$EAPHP#$vPHP#")
             else
-                cmd=$(echo $cmd | sed "s#$EAPHP#$DEFAULT_PHP#")
+                CMD=$(echo $CMD | sed "s#$EAPHP#$DEFAULT_PHP#")
             fi
         fi
-		$BIN/v-add-cron-job $NEW_USER "$min" "$hour" "$day" "$month" "$dow" "$cmd"
+		$BIN/v-add-cron-job $NEW_USER "$MIN" "$HOUR" "$DAY" "$MONTH" "$DOW" "$CMD"
 	done < "$CRON_FILE"
 	printf "%sINFO:%s Cron jobs restored for user %s.\n" "$GREEN" "$COLOROFF" "$NEW_USER"
 else
@@ -489,7 +490,7 @@ for OPTION in $OPTIONS; do
         "CRON")
             restore_cron 
             ;;
-        *)
+         *)
             printf "%sWARNING:%s Invalid option %s. You can use ALL, DB, DOMAIN, MAIL, MX o CRON.\n" "$YELLOW" "$COLOROFF" "$OPTION"
             exit 1
             ;;
